services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: container-portainer
    volumes:
        - ./data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 8000:8000
        - 9443:9443
    restart: always